# Generated by Django 4.2.2 on 2023-07-12 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenseName', models.CharField(max_length=100)),
                ('expenseAmount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('orderId', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('saleType', models.CharField(choices=[('POS', 'POS'), ('Online', 'Online')], default='Online', max_length=10)),
                ('quantity', models.IntegerField()),
                ('pricePerItem', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('totalExpenseAmount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('totalOrderAmount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created', models.DateField(auto_now_add=True)),
                ('extraExpense', models.ManyToManyField(null=True, to='sale.saleexpense')),
                ('inventory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventorySales', to='inventory.inventory')),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storeSales', to='inventory.store')),
            ],
        ),
    ]
