# Generated by Django 4.2.2 on 2023-07-12 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userRole', models.CharField(choices=[('POS seller', 'POS seller'), ('Online seller', 'Online seller')], default='Online seller', max_length=20)),
                ('assignedStore', models.ManyToManyField(blank=True, related_name='assignedUsers', to='inventory.store')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userPermissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
