# Generated by Django 4.2.2 on 2023-07-12 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returnType', models.CharField(choices=[('POS', 'POS'), ('Online', 'Online')], default='Online', max_length=10)),
                ('quantity', models.IntegerField()),
                ('created', models.DateField(auto_now_add=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saleReturn', to='sale.sale')),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storeReturns', to='inventory.store')),
            ],
        ),
    ]
