# Generated by Django 4.2.2 on 2023-07-12 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenseName', models.CharField(max_length=100)),
                ('expenseAmount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('grossPricePerItem', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('totalExpenseAmount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('netPricePerItem', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('totalPurchaseAmount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created', models.DateField(auto_now_add=True)),
                ('extraExpense', models.ManyToManyField(null=True, to='purchase.purchaseexpense')),
                ('inventory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventoryPurchases', to='inventory.inventory')),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storePurchases', to='inventory.store')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplierInventory', to='inventory.supplier')),
            ],
        ),
    ]
